name: lint
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.1.0
    - name: Install Dependencies
      run: bun install
    - name: Run ESLint
      run: bun run lint
